language: bash

services:
  - docker

before_install: >
  docker run -dit -h "mail.example.com" --name="easymail" -v /etc/ssl/certs/:/etc/ssl/certs/ ubuntu:14.04 /bin/sh -c "if [ -f /run.sh ]; then bash /run.sh; fi; exec /bin/bash" &&
  docker exec easymail apt-get update &&
  docker exec easymail apt-get install git -y &&
  docker exec easymail git clone https://github.com/runeasymail/easymail.git /easymail &&
  docker exec easymail echo 'HOSTNAME: test.exmaple.com' > /easymail/easy-mail-install.config




script:
    - bash install.sh
