language: bash

services:
  - docker

before_install: >
  docker run -dit -v /home/travis/build/runeasymail/easymail/:/easymail -p=110:110 -p=25:25 -p=995:995 -p=80:80 -p=443:443 -p=587:587 -p=993:993 -p=143:143 -p=465:465 -h "mail.example.com" --name="easymail" -v /etc/ssl/certs/:/etc/ssl/certs/ ubuntu:16.04 /bin/sh -c "if [ -f /run.sh ]; then bash /run.sh; fi; exec /bin/bash" &&
  echo 'HOSTNAME: test.exmaple.com' > easy-mail-install.config &&
  echo 'PASSWORD: testpassword' >> easy-mail-install.config &&
  echo 'IS_ON_DOCKER: y' >> easy-mail-install.config &&
  echo 'SSL_INSTALL_OWN: n' >> easy-mail-install.config &&
  echo 'USE_LETSENCRYPT: n' >> easy-mail-install.config

script:
    - docker exec easymail bash /easymail/install.sh -c /easymail/easy-mail-install.config
