language: bash

services:
  - docker

before_install: >
  echo 'HOSTNAME: test.exmaple.com' > easy-mail-install.config

script:
    - docker run -it -v /home/travis/build/runeasymail/easymail/:/easymail -p=110:110 -p=25:25 -p=995:995 -p=80:80 -p=443:443 -p=587:587 -p=993:993 -p=143:143 -p=465:465 -h "test.exmaple.com" --name="easymail" -v /etc/ssl/certs/:/etc/ssl/certs/ ubuntu:16.04 /bin/sh -c "bash /easymail/install.sh -c /easymail/easy-mail-install.config"
    - docker start easymail
    - docker exec easymail bash /easymail/post_install.sh
 
# just for testing
    - docker commit easymail easymail-img
    - docker rm easymail
    - docker run -itd -p=110:110 -p=25:25 -p=995:995 -p=80:80 -p=443:443 -p=587:587 -p=993:993 -p=143:143 -p=465:465 -h "test.exmaple.com" --name="easymail" easymail-img /bin/sh -c "if [ -f /run.sh ]; then bash /run.sh; fi; exec /bin/bash"
    - sleep 10
    - docker exec easymail wget --no-check-certificate https://test.exmaple.com
    - docker exec easymail wget --no-check-certificate https://test.exmaple.com/api/ping
    
    # uncomment after integration GUI
    #- docker exec easymail wget --no-check-certificate https://test.exmaple.com/admin/
